import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QWidget,QApplication
from PyQt5.QtGui import QFont
from PyQt5.QtGui import QStandardItemModel
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel
from PyQt5 import uic
from PyQt5.QtCore import QTimer, Qt
#import RPi.GPIO as GPIO
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(711, 513)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(1, 0, 711, 511))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label1 = QtWidgets.QLabel(self.widget)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.horizontalLayout_9.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.widget)
        self.label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.horizontalLayout_9.addWidget(self.label2)
        self.label3 = QtWidgets.QLabel(self.widget)
        self.label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.horizontalLayout_9.addWidget(self.label3)
        self.label4 = QtWidgets.QLabel(self.widget)
        self.label4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.horizontalLayout_9.addWidget(self.label4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2.addWidget(self.widget1)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label21 = QtWidgets.QLabel(self.widget)
        self.label21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label21.setAlignment(QtCore.Qt.AlignCenter)
        self.label21.setObjectName("label21")
        self.verticalLayout.addWidget(self.label21)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label5 = QtWidgets.QLabel(self.widget)
        self.label5.setObjectName("label5")
        self.horizontalLayout.addWidget(self.label5)
        self.label6 = QtWidgets.QLabel(self.widget)
        self.label6.setObjectName("label6")
        self.horizontalLayout.addWidget(self.label6)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label7 = QtWidgets.QLabel(self.widget)
        self.label7.setObjectName("label7")
        self.horizontalLayout_2.addWidget(self.label7)
        self.label8 = QtWidgets.QLabel(self.widget)
        self.label8.setObjectName("label8")
        self.horizontalLayout_2.addWidget(self.label8)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label9 = QtWidgets.QLabel(self.widget)
        self.label9.setObjectName("label9")
        self.horizontalLayout_3.addWidget(self.label9)
        self.label10 = QtWidgets.QLabel(self.widget)
        self.label10.setObjectName("label10")
        self.horizontalLayout_3.addWidget(self.label10)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label11 = QtWidgets.QLabel(self.widget)
        self.label11.setObjectName("label11")
        self.horizontalLayout_4.addWidget(self.label11)
        self.label12 = QtWidgets.QLabel(self.widget)
        self.label12.setObjectName("label12")
        self.horizontalLayout_4.addWidget(self.label12)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 3)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_11.setStretch(0, 20)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label13 = QtWidgets.QLabel(self.widget)
        self.label13.setObjectName("label13")
        self.horizontalLayout_5.addWidget(self.label13)
        self.label14 = QtWidgets.QLabel(self.widget)
        self.label14.setObjectName("label14")
        self.horizontalLayout_5.addWidget(self.label14)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label15 = QtWidgets.QLabel(self.widget)
        self.label15.setObjectName("label15")
        self.horizontalLayout_6.addWidget(self.label15)
        self.label16 = QtWidgets.QLabel(self.widget)
        self.label16.setObjectName("label16")
        self.horizontalLayout_6.addWidget(self.label16)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label17 = QtWidgets.QLabel(self.widget)
        self.label17.setObjectName("label17")
        self.horizontalLayout_7.addWidget(self.label17)
        self.label18 = QtWidgets.QLabel(self.widget)
        self.label18.setObjectName("label18")
        self.horizontalLayout_7.addWidget(self.label18)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label19 = QtWidgets.QLabel(self.widget)
        self.label19.setObjectName("label19")
        self.horizontalLayout_8.addWidget(self.label19)
        self.label20 = QtWidgets.QLabel(self.widget)
        self.label20.setObjectName("label20")
        self.horizontalLayout_8.addWidget(self.label20)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 20)
        self.verticalLayout_3.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "垃圾分类"))
        self.label_25.setText(_translate("Form", "智能垃圾分类"))
        self.label1.setText(_translate("Form", "数量"))
        self.label2.setText(_translate("Form", "无"))
        self.label3.setText(_translate("Form", "识别垃圾种类"))
        self.label4.setText(_translate("Form", "0"))
        self.label21.setText(_translate("Form", "垃圾数量"))
        self.label5.setText(_translate("Form", "有害垃圾"))
        self.label6.setText(_translate("Form", "0"))
        self.label7.setText(_translate("Form", "可回收垃圾"))
        self.label8.setText(_translate("Form", "0"))
        self.label9.setText(_translate("Form", "厨余垃圾"))
        self.label10.setText(_translate("Form", "0"))
        self.label11.setText(_translate("Form", "其他垃圾"))
        self.label12.setText(_translate("Form", "0"))
        self.label13.setText(_translate("Form", "有害垃圾"))
        self.label14.setText(_translate("Form", "空载"))
        self.label15.setText(_translate("Form", "可回收垃圾"))
        self.label16.setText(_translate("Form", "空载"))
        self.label17.setText(_translate("Form", "厨余垃圾"))
        self.label18.setText(_translate("Form", "空载"))
        self.label19.setText(_translate("Form", "其他垃圾"))
        self.label20.setText(_translate("Form", "空载"))

def serial_receive(data):
    global label6,label8,label10,label12

    # 更新垃圾桶标签的内容
    if data == "1":
        current_value = int(label6.text())
        label6.setText(str(current_value + 1))
    elif data == "2":
        current_value = int(label8.text())
        label8.setText(str(current_value + 1))
    elif data == "3":
        current_value = int(label10.text())
        label10.setText(str(current_value + 1))
    elif data == "4":
        current_value = int(label12.text())
        label12.setText(str(current_value + 1))

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
