# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_distancetest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_lx(object):
    def setupUi(self, Dialog_lx):
        Dialog_lx.setObjectName("Dialog_lx")
        Dialog_lx.resize(952, 865)
        self.label = QtWidgets.QLabel(Dialog_lx)
        self.label.setGeometry(QtCore.QRect(370, 820, 148, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setLineWidth(6)
        self.label.setObjectName("label")
        self.distanceEdit = QtWidgets.QLineEdit(Dialog_lx)
        self.distanceEdit.setGeometry(QtCore.QRect(0, 750, 951, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.distanceEdit.setFont(font)
        self.distanceEdit.setObjectName("distanceEdit")
        self.getdata = QtWidgets.QPushButton(Dialog_lx)
        self.getdata.setGeometry(QtCore.QRect(710, 820, 241, 51))
        self.getdata.setObjectName("getdata")
        self.stop = QtWidgets.QPushButton(Dialog_lx)
        self.stop.setGeometry(QtCore.QRect(0, 820, 211, 51))
        self.stop.setObjectName("stop")
        self.listWidget = QtWidgets.QListWidget(Dialog_lx)
        self.listWidget.setGeometry(QtCore.QRect(60, 390, 821, 361))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.wgt_player = QVideoWidget(Dialog_lx)
        self.wgt_player.setGeometry(QtCore.QRect(40, 10, 871, 381))
        self.wgt_player.setObjectName("wgt_player")

        self.retranslateUi(Dialog_lx)
        self.getdata.clicked.connect(Dialog_lx.getdatastart)#绑定点击事件函数
        self.stop.clicked.connect(Dialog_lx.timerstop)#绑定点击事件函数
        QtCore.QMetaObject.connectSlotsByName(Dialog_lx)

    def retranslateUi(self, Dialog_lx):
        _translate = QtCore.QCoreApplication.translate
        Dialog_lx.setWindowTitle(_translate("Dialog_lx", "Dialog"))
        self.label.setText(_translate("Dialog_lx", "分类结果"))
        self.getdata.setText(_translate("Dialog_lx", "开始"))
        self.stop.setText(_translate("Dialog_lx", "停止"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
